# Generated by Django 5.2.6 on 2025-09-11 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0002_lesson_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="material",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documents/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "doc", "docx", "txt", "xls", "xlsx"]
                    )
                ],
                verbose_name="Материал к уроку",
            ),
        ),
    ]
