# Generated by Django 5.2.6 on 2025-09-12 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0004_test_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="test",
        ),
        migrations.AddField(
            model_name="test",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="education.lesson",
                verbose_name="Урок",
            ),
        ),
    ]
